"""Update WorkoutPlan and UserWorkoutProgress models to use string days

Revision ID: 18856be4600b
Revises: 689228393fda
Create Date: 2024-12-29 15:44:45.689248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18856be4600b'
down_revision = '689228393fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
# Inside the `upgrade` function
    with op.batch_alter_table('strength_training', schema=None) as batch_op:
        batch_op.alter_column(
            'effort_level',
            existing_type=sa.String(),
            type_=sa.Integer(),
            nullable=False,
            postgresql_using='effort_level::integer'
        )


    with op.batch_alter_table('user_workout_progress', schema=None) as batch_op:
        batch_op.alter_column('current_day',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_plan', schema=None) as batch_op:
        batch_op.alter_column('day',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('user_workout_progress', schema=None) as batch_op:
        batch_op.alter_column('current_day',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('strength_training', schema=None) as batch_op:
        batch_op.alter_column('effort_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
