"""generation date added'



Revision ID: 20e97a1b9148
Revises: 18856be4600b
Create Date: 2024-12-29 17:03:53.395841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20e97a1b9148'
down_revision = '18856be4600b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_workout_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_date', sa.Date(), nullable=True))
        batch_op.drop_column('last_updated')
        batch_op.drop_column('current_day')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_workout_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_day', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('generation_date')

    # ### end Alembic commands ###
